// <auto-generated />
using System;
using LCode.Resume.Online.DataBase.Contextos.v1_0;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LCode.Resume.Online.DataBase.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211118141910_Add SocialNetwork_Icon_Code_string")]
    partial class AddSocialNetwork_Icon_Code_string
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("resume")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Category_Portfolio", b =>
                {
                    b.Property<Guid>("Guid_Category_Portolio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code_Figure")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Group_Code")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Guid_Category_Portolio");

                    b.ToTable("Category_Portfolio");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.General_Information", b =>
                {
                    b.Property<Guid>("Guid_Resume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ActualLocation")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Domain")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Guid_Resume");

                    b.ToTable("General_Information");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Portfolio", b =>
                {
                    b.Property<Guid>("Guid_Portfolio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("Guid_Category_Portolio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Guid_Resume")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link_Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Guid_Portfolio");

                    b.HasIndex("Guid_Category_Portolio");

                    b.HasIndex("Guid_Resume");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Resume_Extra_Skills", b =>
                {
                    b.Property<Guid>("Guid_Resume_Extra_Skill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("Guid_Resume")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Percent_Experience")
                        .HasColumnType("smallint");

                    b.Property<string>("Skill_Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Skill_Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Guid_Resume_Extra_Skill");

                    b.HasIndex("Guid_Resume");

                    b.ToTable("Resume_Extra_Skills");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Resume_Knowledge_General", b =>
                {
                    b.Property<Guid>("Guid_Resume_Section")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("Guid_Resume")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.HasKey("Guid_Resume_Section");

                    b.HasIndex("Guid_Resume");

                    b.ToTable("Resume_Knowledge_General");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Resume_Section", b =>
                {
                    b.Property<Guid>("Guid_Resume_Section")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("Guid_Resume")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Institution_Company")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Guid_Resume_Section");

                    b.HasIndex("Guid_Resume");

                    b.ToTable("Resume_Section");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Social_Networks", b =>
                {
                    b.Property<Guid>("Guid_SocialNetwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("Guid_Resume")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialNetwork_Icon_Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid_SocialNetwork");

                    b.HasIndex("Guid_Resume");

                    b.ToTable("Social_Networks");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.WhatIDo", b =>
                {
                    b.Property<Guid>("Guid_WhatIDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("Guid_Resume")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Guid_WhatIDo");

                    b.HasIndex("Guid_Resume");

                    b.ToTable("WhatIDo");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Portfolio", b =>
                {
                    b.HasOne("LCode.Resume.Online.Models.v1_0.Category_Portfolio", "Category_Portfolio")
                        .WithMany()
                        .HasForeignKey("Guid_Category_Portolio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCode.Resume.Online.Models.v1_0.General_Information", "General_Information")
                        .WithMany()
                        .HasForeignKey("Guid_Resume")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category_Portfolio");

                    b.Navigation("General_Information");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Resume_Extra_Skills", b =>
                {
                    b.HasOne("LCode.Resume.Online.Models.v1_0.General_Information", "General_Information")
                        .WithMany()
                        .HasForeignKey("Guid_Resume")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General_Information");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Resume_Knowledge_General", b =>
                {
                    b.HasOne("LCode.Resume.Online.Models.v1_0.General_Information", "General_Information")
                        .WithMany()
                        .HasForeignKey("Guid_Resume")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General_Information");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Resume_Section", b =>
                {
                    b.HasOne("LCode.Resume.Online.Models.v1_0.General_Information", "General_Information")
                        .WithMany()
                        .HasForeignKey("Guid_Resume")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General_Information");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.Social_Networks", b =>
                {
                    b.HasOne("LCode.Resume.Online.Models.v1_0.General_Information", "General_Information")
                        .WithMany()
                        .HasForeignKey("Guid_Resume")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General_Information");
                });

            modelBuilder.Entity("LCode.Resume.Online.Models.v1_0.WhatIDo", b =>
                {
                    b.HasOne("LCode.Resume.Online.Models.v1_0.General_Information", "General_Information")
                        .WithMany()
                        .HasForeignKey("Guid_Resume")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General_Information");
                });
#pragma warning restore 612, 618
        }
    }
}
